# Generating Data with Numpy

In [1]:
import numpy as np

### np.empty(), np.zeros(), np.ones(), np.full()

In [2]:
array_empty=np.empty(shape=(2,3))
#the above code will create an empty two by three array
array_empty

array([[1.05118288e-153, 2.85168689e-109, 7.67582751e+170],
       [1.05161522e-153, 9.54899498e-259, 7.04142211e-009]])

But the problem with the above code is that, it can sometimes give us some random values including 
numbers greater than o. This is where  we have to us np.zeros if we want to obtain only zeros

In [3]:
emptyArray=np.empty(shape=(10,10))
emptyArray

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Now check the code below for np.zeros

In [4]:
array_0s=np.zeros(shape=(2,3))
array_0s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
array_0s=np.ones(shape=(2,3),dtype=str)
array_0s

array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [6]:
array_empty=np.empty(shape=(10,10))
array_empty

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
array_0s=np.zeros(shape=(2,3),dtype=np.int8)
array_0s

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

another function used in filling our array with identical numbers is the np.full function
It goes this way

In [8]:
array_fill=np.full(shape=(2,3),fill_value=2)
array_fill

array([[2, 2, 2],
       [2, 2, 2]])

In [9]:
array_fill=np.full(shape=(3,4),fill_value=7)
array_fill

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

so basically we can use np.full to fill any array with any numbers of our choice

### "_like" functions

In [12]:
matrix_A=np.array([[1,3,4,5,6],[3,5,5,6,7],[6,7,8,9,8]])
matrix_A

array([[1, 3, 4, 5, 6],
       [3, 5, 5, 6, 7],
       [6, 7, 8, 9, 8]])

In [15]:
array_empty_like=np.empty_like(matrix_A)
array_empty_like


array([[  0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0],
       [500,   0,   0,   0,   0]])

### np.arange()

## Random Generators

### Defining Random Generators

### Generating Integers, Probabilities and Random Choices

### Generating Arrays From Known Distributions

https://numpy.org/doc/stable/reference/random/generator

### Applications of Random Generators