# Generating Data with Numpy

In [1]:
import numpy as np

### np.empty(), np.zeros(), np.ones(), np.full()

In [2]:
array_empty=np.empty(shape=(2,3))
#the above code will create an empty two by three array
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

But the problem with the above code is that, it can sometimes give us some random values including 
numbers greater than o. This is where  we have to us np.zeros if we want to obtain only zeros

In [3]:
emptyArray=np.empty(shape=(10,10))
emptyArray

array([[1.42237375e+214, 8.73774865e+183, 9.82723909e-153,
        4.86887888e+170, 9.08367217e+223, 5.50409697e+257,
        1.32851841e+179, 2.32160957e-152, 5.44367617e+156,
        6.01347002e-154],
       [3.17261480e+180, 6.01334434e-154, 9.87762528e+247,
        4.46811730e-091, 2.44041296e-154, 9.10016855e+276,
        1.03475054e-028, 1.17574872e+214, 9.19596581e+170,
        1.81450398e-152],
       [8.06827464e-090, 1.13088181e+257, 3.06836100e+257,
        6.01346953e-154, 1.87633123e-152, 3.32230853e+257,
        2.35288464e+251, 3.10423937e+169, 1.68821486e+195,
        6.01099969e+175],
       [1.94210174e+227, 2.68206260e-260, 7.70858946e+218,
        6.01334668e-154, 4.47593816e-091, 7.01413727e-009,
        3.74168445e+233, 2.59345444e+161, 2.58400946e+161,
        2.53160900e-086],
       [4.35287203e-114, 4.46009532e+217, 7.65775292e-096,
        1.15297918e-259, 1.12547821e-153, 6.01347002e-154,
        6.01347002e-154, 6.01347002e-154, 6.01347002e-154,
        6.0

Now check the code below for np.zeros

In [4]:
array_0s=np.zeros(shape=(2,3))
array_0s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
array_0s=np.ones(shape=(2,3),dtype=str)
array_0s

array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [6]:
array_empty=np.empty(shape=(10,10))
array_empty

array([[1.42237375e+214, 8.73774865e+183, 9.82723909e-153,
        4.86887888e+170, 9.08367217e+223, 5.50409697e+257,
        1.32851841e+179, 2.32160957e-152, 5.44367617e+156,
        6.01347002e-154],
       [3.17261480e+180, 6.01334434e-154, 9.87762528e+247,
        4.46811730e-091, 2.44041296e-154, 9.10016855e+276,
        1.03475054e-028, 1.17574872e+214, 9.19596581e+170,
        1.81450398e-152],
       [8.06827464e-090, 1.13088181e+257, 3.06836100e+257,
        6.01346953e-154, 1.87633123e-152, 3.32230853e+257,
        2.35288464e+251, 3.10423937e+169, 1.68821486e+195,
        6.01099969e+175],
       [1.94210174e+227, 2.68206260e-260, 7.70858946e+218,
        6.01334668e-154, 4.47593816e-091, 7.01413727e-009,
        3.74168445e+233, 2.59345444e+161, 2.58400946e+161,
        2.53160900e-086],
       [4.35287203e-114, 4.46009532e+217, 7.65775292e-096,
        1.15297918e-259, 1.12547821e-153, 6.01347002e-154,
        6.01347002e-154, 6.01347002e-154, 6.01347002e-154,
        6.0

In [7]:
array_0s=np.zeros(shape=(2,3),dtype=np.int8)
array_0s

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

another function used in filling our array with identical numbers is the np.full function
It goes this way

In [8]:
array_fill=np.full(shape=(2,3),fill_value=2)
array_fill

array([[2, 2, 2],
       [2, 2, 2]])

In [9]:
array_fill=np.full(shape=(3,4),fill_value=7)
array_fill

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

so basically we can use np.full to fill any array with any numbers of our choice

### "_like" functions

In [10]:
matrix_A=np.array([[1,3,4,5,6],[3,5,5,6,7],[6,7,8,9,8]])
matrix_A

array([[1, 3, 4, 5, 6],
       [3, 5, 5, 6, 7],
       [6, 7, 8, 9, 8]])

In [11]:
array_empty_like=np.empty_like(matrix_A)
array_empty_like


array([[   0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0],
       [1440,    0,    0,    0,    0]])

In [12]:
 array_zeros_like=np.zeros_like(matrix_A)
array_zeros_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### np.arange()

The np.arange function is used to generate a sequence of consecutive numbers

In [13]:
array_rng=np.arange(1,30,3)
array_rng

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

## Random Generators

### Defining Random Generators

In [14]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

#in actual sense , their full names are np.random.Generator and numpy.random
# PCG stands for Permutation Congruential Generator

In [15]:
array_RG=gen(pcg())
array_RG.normal(size=5)
#this generates a random number from the standard normal distribution

array([ 0.40363671, -0.52305138,  0.54546222,  0.7980638 ,  0.08969348])

In [16]:
array_RG=gen(pcg())
array_RG.normal(size=(5,5))
#The only problem with thi code is that every time we run this cell,  we will always get different output
#in that case we need to introduce seed=365 to the pcg method

array([[ 0.85032151,  2.38326688,  1.54955448,  0.61734068, -1.49464802],
       [-0.23908075,  1.60682305, -1.36891535, -0.687979  , -0.28674652],
       [ 0.53390001,  0.68838262, -0.78252273,  1.62011725,  0.17897661],
       [ 1.01587515,  0.9525451 , -1.71798305, -1.35085723,  2.08903407],
       [-0.45655284, -0.01125838, -0.56527673, -0.50462143, -1.07322463]])

In [17]:
array_RG=gen(pcg(seed=365))
array_RG.normal(size=(5,5))
#sometimes we want to generate some random dataset to test our model 



array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])

With the above code , we will always get the same output. Hence we can always use that to generate 
some random dataset to test our model

### Generating Integers, Probabilities and Random Choices

In [ ]:
array_RG=gen(pcg(seed=365))
array_RG.integers(10,)

### Generating Arrays From Known Distributions

https://numpy.org/doc/stable/reference/random/generator

### Applications of Random Generators