# Generating Data with Numpy

In [1]:
import numpy as np

### np.empty(), np.zeros(), np.ones(), np.full()

In [2]:
array_empty=np.empty(shape=(2,3))
#the above code will create an empty two by three array
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

But the problem with the above code is that, it can sometimes give us some random values including 
numbers greater than o. This is where  we have to us np.zeros if we want to obtain only zeros

In [3]:
emptyArray=np.empty(shape=(10,10))
emptyArray

array([[1.13352043e-153, 7.34728222e+228, 2.15779010e+185,
        1.27617599e-152, 1.17549387e+214, 7.72482858e+228,
        6.01346953e-154, 1.57430847e+161, 4.65541789e-072,
        5.98129759e-154],
       [1.06758000e+224, 4.46811730e-091, 5.98149672e-154,
        3.43515227e+228, 6.01347002e-154, 2.28896090e+243,
        1.28037489e-152, 2.34783525e+251, 4.83245960e+276,
        1.71963045e+238],
       [1.49005471e+195, 5.70727135e+188, 6.01334657e-154,
        2.11776372e+214, 1.05893702e-153, 7.13144174e+252,
        3.45060540e-085, 1.49003466e+195, 4.83245960e+276,
        7.33956123e+223],
       [2.31589513e+251, 6.01346953e-154, 9.92152605e+247,
        4.91347540e+252, 2.66062477e-260, 1.27661731e-152,
        6.01334659e-154, 4.47593816e-091, 1.15305479e+214,
        2.46818315e-154],
       [9.10016855e+276, 1.09854920e+248, 1.27734658e-152,
        3.98220482e+209, 8.58149566e+170, 2.66061857e-260,
        5.29965388e+180, 4.46811730e-091, 6.01346953e-154,
        8.7

Now check the code below for np.zeros

In [4]:
array_0s=np.zeros(shape=(2,3))
array_0s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
array_0s=np.ones(shape=(2,3),dtype=str)
array_0s

array([['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [6]:
array_empty=np.empty(shape=(10,10))
array_empty

array([[1.13352043e-153, 7.34728222e+228, 2.15779010e+185,
        1.27617599e-152, 1.17549387e+214, 7.72482858e+228,
        6.01346953e-154, 1.57430847e+161, 4.65541789e-072,
        5.98129759e-154],
       [1.06758000e+224, 4.46811730e-091, 5.98149672e-154,
        3.43515227e+228, 6.01347002e-154, 2.28896090e+243,
        1.28037489e-152, 2.34783525e+251, 4.83245960e+276,
        1.71963045e+238],
       [1.49005471e+195, 5.70727135e+188, 6.01334657e-154,
        2.11776372e+214, 1.05893702e-153, 7.13144174e+252,
        3.45060540e-085, 1.49003466e+195, 4.83245960e+276,
        7.33956123e+223],
       [2.31589513e+251, 6.01346953e-154, 9.92152605e+247,
        4.91347540e+252, 2.66062477e-260, 1.27661731e-152,
        6.01334659e-154, 4.47593816e-091, 1.15305479e+214,
        2.46818315e-154],
       [9.10016855e+276, 1.09854920e+248, 1.27734658e-152,
        3.98220482e+209, 8.58149566e+170, 2.66061857e-260,
        5.29965388e+180, 4.46811730e-091, 6.01346953e-154,
        8.7

In [7]:
array_0s=np.zeros(shape=(2,3),dtype=np.int8)
array_0s

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

another function used in filling our array with identical numbers is the np.full function
It goes this way

In [8]:
array_fill=np.full(shape=(2,3),fill_value=2)
array_fill

array([[2, 2, 2],
       [2, 2, 2]])

In [9]:
array_fill=np.full(shape=(3,4),fill_value=7)
array_fill

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

so basically we can use np.full to fill any array with any numbers of our choice

### "_like" functions

In [10]:
matrix_A=np.array([[1,3,4,5,6],[3,5,5,6,7],[6,7,8,9,8]])
matrix_A

array([[1, 3, 4, 5, 6],
       [3, 5, 5, 6, 7],
       [6, 7, 8, 9, 8]])

In [11]:
array_empty_like=np.empty_like(matrix_A)
array_empty_like


array([[      0,       0,       0,       0,       0],
       [      0,       0,       0,       0,       0],
       [   1468,       0,       0, 3342433,       0]])

In [12]:
 array_zeros_like=np.zeros_like(matrix_A)
array_zeros_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### np.arange()

The np.arange function is used to generate a sequence of consecutive numbers

In [14]:
array_rng=np.arange(1,30,3)
array_rng

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

## Random Generators

### Defining Random Generators

In [15]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

#in actual sense , their full names are np.random.Generator and numpy.random

### Generating Integers, Probabilities and Random Choices

### Generating Arrays From Known Distributions

https://numpy.org/doc/stable/reference/random/generator

### Applications of Random Generators