ALL ABOUT NUMPY BASIC OPERATIONS

In [1]:
import numpy as np

In [2]:
array_a=np.array([1,2,3])

In [3]:
array_a

array([1, 2, 3])

In [4]:
array_b=np.array([[1,2,3],[3,4,5],[6,7,8]])

In [5]:
array_b

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.mean(array_b,axis=0)

array([3.33333333, 4.33333333, 5.33333333])

In [7]:
array1=np.array([[1,2,3],[4,5,6]])

In [8]:
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
type(array1)

numpy.ndarray

In [10]:
array1.shape

(2, 3)

In [11]:
list_a=[[1,2,3,6],[4,5,6,8],[7,8,9,9]]

In [12]:
len(list_a)

3

In [13]:
type(list_a)

list

In [14]:
type(array_a)

numpy.ndarray

In [15]:
confuse=np.array([1,2,3])

In [16]:
confuse

array([1, 2, 3])

In [17]:
len(list_a)

3

In [18]:
len(list_a[0])

4

In [19]:
len(list_a)

3

In [20]:
len(list_a[0])

4

In [21]:
len(list_a[2])

4

In [22]:
print(list_a)

[[1, 2, 3, 6], [4, 5, 6, 8], [7, 8, 9, 9]]


In [23]:
p=list_a

In [24]:
np.array(p)

array([[1, 2, 3, 6],
       [4, 5, 6, 8],
       [7, 8, 9, 9]])

In [25]:
list_b=list_a[0]+list_a[1]

In [26]:
list_b

[1, 2, 3, 6, 4, 5, 6, 8]

In [27]:
array_b=array_a[0]+array_a[1]

In [28]:
array_b

3

In [29]:
np.sqrt(array_a)

array([1.        , 1.41421356, 1.73205081])

NUMPY FUNDAMENTALS

In [30]:
array_z=np.array([[2,3,4,5],[5,6,7,78],[3,4,7,5]])

In [31]:
array_z

array([[ 2,  3,  4,  5],
       [ 5,  6,  7, 78],
       [ 3,  4,  7,  5]])

In [32]:
array_z[0]

array([2, 3, 4, 5])

In [33]:
array_z[0][1]

3

In [34]:
array_z[2][2]

7

In [35]:
array_z[2][3]

5

In [36]:
array_z[-1]

array([3, 4, 7, 5])

In [37]:
array_z[-2]

array([ 5,  6,  7, 78])

We can assign values to individual elements of an array. See the code below. 

In [38]:
array_z[0,3]=9

In [39]:
array_z

array([[ 2,  3,  4,  9],
       [ 5,  6,  7, 78],
       [ 3,  4,  7,  5]])

To set all values of column 1 to 9 , we enter the command below. We have changed the fourth element of the first row from 5 to 9

In [40]:
array_z[:,1]=9

In [41]:

array_z

array([[ 2,  9,  4,  9],
       [ 5,  9,  7, 78],
       [ 3,  9,  7,  5]])

We want to now set all values of row 0 to 3

In [42]:
array_z[0]=3

In [43]:
array_z

array([[ 3,  3,  3,  3],
       [ 5,  9,  7, 78],
       [ 3,  9,  7,  5]])

We want to now set entire rows of an array to a list

In [44]:
someList=array_z[0]

In [45]:
someList

array([3, 3, 3, 3])

In [46]:
another_list=array_z[2]

In [47]:
another_list

array([3, 9, 7, 5])

What if we want to set all values of the array equall to a single number? Let's see

In [48]:
array_z

array([[ 3,  3,  3,  3],
       [ 5,  9,  7, 78],
       [ 3,  9,  7,  5]])

In [49]:
array_z[:]=1

In [50]:
array_z

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [51]:
another_list

array([1, 1, 1, 1])

Adding a value to a 1D array

In [52]:
another_list+5

array([6, 6, 6, 6])

How about if we add 5 to a 2D array? what will happen?

In [53]:
array_z+5

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

It works that way as well. In fact, we can compute all kinds of mathematical operations of arrays, operations like the addition we just did, subtraction, multiplication and division

But there is more we can do with arrays. We can add one dimensional arrays to two dimensional arrays
as shown below

In [54]:
array_b=([7,5,6,7])

In [55]:
array_c=np.array([[2,3,4,5],[5,6,7,78],[3,4,7,5]])

In [56]:
array_b+array_c

array([[ 9,  8, 10, 12],
       [12, 11, 13, 85],
       [10,  9, 13, 12]])

What happened in the above code was that,each element of array_b was added to the corrresponding 
element in each row of array_c

The default data type of a numpy array is always set to none . But we can set it to a different
data type

In [57]:
array_dtype=np.array([[2,3,4,6,7],[2,34,5,6,4]],dtype=np.complex64)

In [58]:
array_dtype

array([[ 2.+0.j,  3.+0.j,  4.+0.j,  6.+0.j,  7.+0.j],
       [ 2.+0.j, 34.+0.j,  5.+0.j,  6.+0.j,  4.+0.j]], dtype=complex64)

In [59]:
array_dtype=np.array([[2,3,4,6,7],[2,4,5,6,4]],dtype=str)

In [60]:
array_dtype

array([['2', '3', '4', '6', '7'],
       ['2', '4', '5', '6', '4']], dtype='<U1')

Characteristics of numpy functions

Broadcasting

In [61]:
array_a=np.array([1,2,3])
array_a

array([1, 2, 3])

In [62]:
array_b=np.array([[2],[3]])
array_b

array([[2],
       [3]])

In [63]:
matrix_c=np.array([[2,3,4],[6,7,8]])
matrix_c

array([[2, 3, 4],
       [6, 7, 8]])

Type Casting

This is the act of changing the data type of an array to a different data type. Example is indicated below

Broad Casting
This refers to working with arrays that have different shapes like the code below

In [64]:
np.add(array_b,matrix_c,dtype=np.float64)

array([[ 4.,  5.,  6.],
       [ 9., 10., 11.]])

In [65]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [66]:
array2=np.array([[1],[2]])
array2

array([[1],
       [2]])

In [67]:
array3=np.array([[3,4,5],[3,2,5]])
array3

array([[3, 4, 5],
       [3, 2, 5]])

In [68]:
np.add(array1,array3)

array([[4, 6, 8],
       [4, 4, 8]])

Type Casting
This is the act of taking every element of an array and changing it into a specified data type

In [69]:
np.add(array1,array3,dtype='float64')

array([[4., 6., 8.],
       [4., 4., 8.]])

Running a function along a given axis

In [70]:
np.mean(array3,axis=0)

#When we set axis to be equal to 0, we are basically finding the mean for each column of the array

array([3., 3., 5.])

In [71]:
np.mean(array3,axis=1)
# Setting axis=1 lets us find the mean for each row of the array

array([4.        , 3.33333333])

Some Numpy Fundamental Operations to note. Consider the array below

In [72]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
#want to set the last column of this array to 100

In [73]:
array_2D[:,-1]=100

In [74]:
array_2D

array([[ 20,  30,  40,  50, 100],
       [ 43,  54,  65,  76, 100],
       [ 11,  22,  33,  44, 100]])

In [75]:
#Want to then set the first row of the array to 20
#I still haven't gotten a solution though
array_2D[:]=20
array_2D

array([[20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

In [76]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])

In [77]:
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

In [78]:
array_3D[:]=50
#To set all values of array_3D to 50

In [79]:
array_3D

array([[[50, 50, 50, 50, 50],
        [50, 50, 50, 50, 50]],

       [[50, 50, 50, 50, 50],
        [50, 50, 50, 50, 50]]])

Since we've altered the values of our original arrays, we want to re-run the following cells to 
get back our original arrays

In [80]:
array_1D = np.array([10,11,12,13,14])
array_1D

array([10, 11, 12, 13, 14])

In [81]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [82]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

Want to Add 2 to every element of the 3 arrays without overwriting their values

In [83]:
array_1D+2

array([12, 13, 14, 15, 16])

In [84]:
array_2D+2

array([[22, 32, 42, 52, 62],
       [45, 56, 67, 78, 89],
       [13, 24, 35, 46, 57]])

In [85]:
array_3D+2

array([[[ 3,  4,  5,  6,  7],
        [13, 23, 33, 43, 53]],

       [[13, 14, 15, 16, 17],
        [53, 54, 55, 56,  7]]])


Want to multiply the values of each array by 100 without overwriting their values.

In [86]:
array_1D*100

array([1000, 1100, 1200, 1300, 1400])

In [87]:
array_2D*100

array([[2000, 3000, 4000, 5000, 6000],
       [4300, 5400, 6500, 7600, 8700],
       [1100, 2200, 3300, 4400, 5500]])

In [88]:
array_3D*100

array([[[ 100,  200,  300,  400,  500],
        [1100, 2100, 3100, 4100, 5100]],

       [[1100, 1200, 1300, 1400, 1500],
        [5100, 5200, 5300, 5400,  500]]])

Want to add up array_1D and the first row of array_2D

In [89]:
array_1D+array_2D[0]

array([30, 41, 52, 63, 74])

Re-writing array_1D as a string

In [90]:
array_1D = np.array([10,11,12,13,14],dtype=str)
array_1D

array(['10', '11', '12', '13', '14'], dtype='<U2')

Re-writing array_2D as a complex number

In [91]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]],dtype=np.complex128)
array_2D

array([[20.+0.j, 30.+0.j, 40.+0.j, 50.+0.j, 60.+0.j],
       [43.+0.j, 54.+0.j, 65.+0.j, 76.+0.j, 87.+0.j],
       [11.+0.j, 22.+0.j, 33.+0.j, 44.+0.j, 55.+0.j]])

Re-writing array_3D as a 64 bit float

In [92]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]],dtype=np.float64)
array_3D

array([[[ 1.,  2.,  3.,  4.,  5.],
        [11., 21., 31., 41., 51.]],

       [[11., 12., 13., 14., 15.],
        [51., 52., 53., 54.,  5.]]])

In [93]:
array_1D = np.array([10,11,12,13,14])
array_1D

array([10, 11, 12, 13, 14])

In [94]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [95]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

In [96]:
array_2D-array_1D

array([[10, 19, 28, 37, 46],
       [33, 43, 53, 63, 73],
       [ 1, 11, 21, 31, 41]])

In [97]:
array_3D/array_1D

array([[[0.1       , 0.18181818, 0.25      , 0.30769231, 0.35714286],
        [1.1       , 1.90909091, 2.58333333, 3.15384615, 3.64285714]],

       [[1.1       , 1.09090909, 1.08333333, 1.07692308, 1.07142857],
        [5.1       , 4.72727273, 4.41666667, 4.15384615, 0.35714286]]])

Want to use axis argument of the np.mean() function to find the mean for every column of the 2-D array

In [98]:
np.mean(array_2D,axis=0)

array([24.66666667, 35.33333333, 46.        , 56.66666667, 67.33333333])

How about if we do same for every row?

In [99]:
np.mean(array_2D,axis=1)

array([40., 65., 33.])

Want to use axis argument of the np.mean() function to find the mean for every column of the 3-D array

In [100]:
np.mean(array_3D,axis=1)

array([[ 6. , 11.5, 17. , 22.5, 28. ],
       [31. , 32. , 33. , 34. , 10. ]])