ALL ABOUT NUMPY BASIC OPERATIONS

In [1]:
import numpy as np

In [2]:
array_a=np.array([1,2,3])

In [3]:
array_a

array([1, 2, 3])

In [4]:
array_b=np.array([[1,2,3],[3,4,5],[6,7,8]])

In [5]:
array_b

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.mean(array_b,axis=0)

array([3.33333333, 4.33333333, 5.33333333])

In [7]:
array1=np.array([[1,2,3],[4,5,6]])

In [8]:
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
type(array1)

numpy.ndarray

In [10]:
array1.shape

(2, 3)

In [11]:
list_a=[[1,2,3,6],[4,5,6,8],[7,8,9,9]]

In [12]:
len(list_a)

3

In [13]:
type(list_a)

list

In [14]:
type(array_a)

numpy.ndarray

In [15]:
confuse=np.array([1,2,3])

In [16]:
confuse

array([1, 2, 3])

In [17]:
len(list_a)

3

In [18]:
len(list_a[0])

4

In [19]:
len(list_a)

3

In [20]:
len(list_a[0])

4

In [21]:
len(list_a[2])

4

In [22]:
print(list_a)

[[1, 2, 3, 6], [4, 5, 6, 8], [7, 8, 9, 9]]


In [23]:
p=list_a

In [24]:
np.array(p)

array([[1, 2, 3, 6],
       [4, 5, 6, 8],
       [7, 8, 9, 9]])

In [25]:
list_b=list_a[0]+list_a[1]

In [26]:
list_b

[1, 2, 3, 6, 4, 5, 6, 8]

In [27]:
array_b=array_a[0]+array_a[1]

In [28]:
array_b

3

In [29]:
np.sqrt(array_a)

array([1.        , 1.41421356, 1.73205081])

NUMPY FUNDAMENTALS

In [30]:
array_z=np.array([[2,3,4,5],[5,6,7,78],[3,4,7,5]])

In [31]:
array_z

array([[ 2,  3,  4,  5],
       [ 5,  6,  7, 78],
       [ 3,  4,  7,  5]])

In [32]:
array_z[0]

array([2, 3, 4, 5])

In [33]:
array_z[0][1]

3

In [34]:
array_z[2][2]

7

In [35]:
array_z[2][3]

5

In [36]:
array_z[-1]

array([3, 4, 7, 5])

In [37]:
array_z[-2]

array([ 5,  6,  7, 78])

We can assign values to individual elements of an array. See the code below. 

In [38]:
array_z[0,3]=9

In [39]:
array_z

array([[ 2,  3,  4,  9],
       [ 5,  6,  7, 78],
       [ 3,  4,  7,  5]])

To set all values of column 1 to 9 , we enter the command below. We have changed the fourth element of the first row from 5 to 9

In [40]:
array_z[:,1]=9

In [41]:

array_z

array([[ 2,  9,  4,  9],
       [ 5,  9,  7, 78],
       [ 3,  9,  7,  5]])

We want to now set all values of row 0 to 3

In [42]:
array_z[0]=3

In [43]:
array_z

array([[ 3,  3,  3,  3],
       [ 5,  9,  7, 78],
       [ 3,  9,  7,  5]])

We want to now set entire rows of an array to a list

In [44]:
someList=array_z[0]

In [45]:
someList

array([3, 3, 3, 3])

In [46]:
another_list=array_z[2]

In [47]:
another_list

array([3, 9, 7, 5])

What if we want to set all values of the array equall to a single number? Let's see

In [48]:
array_z

array([[ 3,  3,  3,  3],
       [ 5,  9,  7, 78],
       [ 3,  9,  7,  5]])

In [49]:
array_z[:]=1

In [50]:
array_z

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [51]:
another_list

array([1, 1, 1, 1])

Adding a value to a 1D array

In [52]:
another_list+5

array([6, 6, 6, 6])

How about if we add 5 to a 2D array? what will happen?

In [53]:
array_z+5

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

It works that way as well. In fact, we can compute all kinds of mathematical operations of arrays, operations like the addition we just did, subtraction, multiplication and division

But there is more we can do with arrays. We can add one dimensional arrays to two dimensional arrays
as shown below

In [54]:
array_b=([7,5,6,7])

In [55]:
array_c=np.array([[2,3,4,5],[5,6,7,78],[3,4,7,5]])

In [56]:
array_b+array_c

array([[ 9,  8, 10, 12],
       [12, 11, 13, 85],
       [10,  9, 13, 12]])

What happened in the above code was that,each element of array_b was added to the corrresponding 
element in each row of array_c

The default data type of a numpy array is always set to none . But we can set it to a different
data type

In [65]:
array_dtype=np.array([[2,3,4,6,7],[2,34,5,6,4]],dtype=np.complex64)

In [66]:
array_dtype

array([[ 2.+0.j,  3.+0.j,  4.+0.j,  6.+0.j,  7.+0.j],
       [ 2.+0.j, 34.+0.j,  5.+0.j,  6.+0.j,  4.+0.j]], dtype=complex64)

In [70]:
array_dtype=np.array([[2,3,4,6,7],[2,4,5,6,4]],dtype=str)

In [71]:
array_dtype

array([['2', '3', '4', '6', '7'],
       ['2', '4', '5', '6', '4']], dtype='<U1')

Characteristics of numpy functions

Broadcasting

In [82]:
array_a=np.array([1,2,3])
array_a

array([1, 2, 3])

In [83]:
array_b=np.array([[2],[3]])
array_b

array([[2],
       [3]])

In [84]:
matrix_c=np.array([[2,3,4],[6,7,8]])
matrix_c

array([[2, 3, 4],
       [6, 7, 8]])

Type Casting

This is the act of changing the data type of an array to a different data type. Example is indicated below

In [87]:
np.add(array_b,matrix_c,dtype=np.float64)

array([[ 4.,  5.,  6.],
       [ 9., 10., 11.]])