# Working with Arrays

In [1]:
import numpy as np

## Slicing

Slicing is the act of creating a new array by taking chunks of values out of an existing array

In [2]:
matrix_A=np.array([[1,2,3],[4,5,6]])
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

### Basic Slicing

In [4]:
matrix_A[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
matrix_A[0:1]

array([[1, 2, 3]])

The above code tells python to slice from the row with index o and stop right before the row with indeex 1

In [8]:
matrix_A[:1]
#This tells numpy to slice out everything from the begining row to the row with index number 1

array([[1, 2, 3]])

In [ ]:
matrix_A[:,1]
#please note the differences between this and the above code
#this code tells nunpy tot

### Stepwise Slicing

### Conditional Slicing

## Dimensions and the Squeeze Function