# Working with Arrays

In [3]:
import numpy as np

## Slicing

Slicing is the act of creating a new array by taking chunks of values out of an existing array

In [4]:
matrix_A=np.array([[1,2,3],[4,5,6]])
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

### Basic Slicing

In [5]:
matrix_A[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
matrix_A[0:1]

array([[1, 2, 3]])

The above code tells python to slice from the row with index o and stop right before the row with indeex 1

In [7]:
matrix_A[:1]
#This tells numpy to slice out everything from the begining row to the row with index number 1

array([[1, 2, 3]])

In [8]:
matrix_A[:,1]
#please note the differences between this and the above code
#this code tells numpy to slice out the column(instead of row) with index 1
#the differences is the comma inbetween the colon and the number

array([2, 5])

We've been slicing out rows all this while. Now let's see how we can slice out certain columns of an array

In [9]:
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
matrix_A[:,2]
#To slice out column 2

array([3, 6])

In [11]:
matrix_A[:,1:]
#To slice out arrays from column with index 2 to the last column

array([[2, 3],
       [5, 6]])

Now lets see how we can slice out both rows and columns at the same time

In [12]:
matrix_A[1:,1:]
#To slice out from column with index 1 to the end and row with index 1 to the end

array([[5, 6]])

### Stepwise Slicing

Stepwise slicing is a form of slicing where by we slice from one row or
column and jump several steps to slice from another row or column. This form of slicing does not involve slicing from consecutive rows or columns

In [13]:
matrix_B=np.array([[1,1,1,2,0],[3,6,6,7,4],[4,5,3,8,0]])
matrix_B

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [14]:
matrix_B[:,:]

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

### Conditional Slicing

In [15]:
matrix_C=np.array([[1,2,4,5,6],[7,6,7,8,6],[3,3,5,6,7]])
matrix_C

array([[1, 2, 4, 5, 6],
       [7, 6, 7, 8, 6],
       [3, 3, 5, 6, 7]])

Lets slice the first column

In [16]:
matrix_C[:,0]

array([1, 7, 3])

lets slice the last column as well

In [17]:
matrix_C[:,-1]

array([6, 6, 7])

In [18]:
matrix_C[:,0]>2

array([False,  True,  True])

We want to find all values of matrix_C greater than 2

In [20]:
matrix_C[:,:]>2

array([[False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

We want the actual values and not boolean. So let's do this

In [22]:
matrix_C[matrix_C[:,:]>2]
#Now we have all the actual values in our matrix that are greater than two

array([4, 5, 6, 7, 6, 7, 8, 6, 3, 3, 5, 6, 7])

## Dimensions and the Squeeze Function