# Statistsics w/ NumPy

In [1]:
import numpy as np

In [3]:
matrix_A=np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
print(matrix_A)

[[1 0 0 3 1]
 [3 6 6 2 9]
 [4 5 3 8 0]]


### np.mean()

In [5]:
np.mean(matrix_A)
#that is the mean for the entire array
#what if we want the mean for only the first element of the array?

3.4

In [6]:
np.mean(matrix_A[0])

1.0

In [8]:
np.mean(matrix_A[:,0])

2.6666666666666665

Now we want to compute the means of all the columns

In [13]:
np.mean(matrix_A,axis=0)

array([2.66666667, 3.66666667, 3.        , 4.33333333, 3.33333333])

In [14]:
np.mean(matrix_A,axis=1)
#computing the menas of all the rows simultaneously

array([1. , 5.2, 4. ])

### Min & Max Values

In [15]:
matrix_A=np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
print(matrix_A)

[[1 0 0 3 1]
 [3 6 6 2 9]
 [4 5 3 8 0]]


np.mean finds the lowest array along a given axis

np.minimum is a method which requires two input arrays,generates an array which holds the element-wise minimal vallues

In [17]:
np.minimum(matrix_A[0],matrix_A[2])
#So this code finds the minimal values, comparing the first and the last rows of the array

array([1, 0, 0, 3, 0])

### Statistical Order Functions 

The first statistical order we want to look at is peak to peak-np.ptp , which returns
the differenece between the hightest and the lowest value within an array

In [18]:
matrix_A=np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
print(matrix_A)

[[1 0 0 3 1]
 [3 6 6 2 9]
 [4 5 3 8 0]]


In [19]:
np.ptp(matrix_A)

9

In [20]:
np.ptp(matrix_A,axis=0)
#we want to find the difference between the highest and the lowest value within the coluumn

array([3, 6, 6, 6, 9])

In [21]:
np.ptp(matrix_A,axis=1)
#we want to find the difference between the highest and the lowest value within the row

array([3, 7, 8])

### np.percentile(). This function is used to return a value that is greater than the corresponding % of the dataset. 
### for example, 70th percentile means 70% through the dataset after sorting the values from the lowest to the highest

In [24]:
#Lets first sort the vaues in matrix_A

In [25]:
np.sort(matrix_A,axis=None)

array([0, 0, 0, 1, 1, 2, 3, 3, 3, 4, 5, 6, 6, 8, 9])

In [28]:
np.percentile(matrix_A,70)
#this is the 70th percentile of matrix_A

4.799999999999999

In [30]:
np.percentile(matrix_A,70,interpolation='midpoint')


4.5

From the sorted array of matrix_A, we see that the 70th percentile is between 4 and 5, so we can set the 
the interpolation to be midpoint so that we have a our percentile to be at the midpoint between the lowest value 
and the highest value
We can also set the interpolation to be lower or higher. Let's do this...

In [31]:
np.percentile(matrix_A,70,interpolation='lower')
#the lower of the two values is 4


4

In [33]:
np.percentile(matrix_A,70,interpolation='higher')

# the higher of the two values is 5

5

However, it is recommended that your interpolation be set to 'nearest'
in that case, we will find the nearest value of the percentile within the dataset. Lets do this...

In [34]:
np.percentile(matrix_A,70,interpolation='nearest')


5

np.quantile is also related to np.percentile. The only difference between the two is that, percentile computes in terms
of percentages whilst quantiles computes in terms decimal between 0 and 1

In [42]:
np.quantile(matrix_A,0.70,interpolation='nearest')

5

### Averages and Variances

### Correlation

### Histograms

### NaN-Equivalents